### ISSUE TITLE
Insert logo part

### ISSUE THREAD

**Issue by josheghani-dev** [anetwork/dynamicad-php-client#3]
hey,

The image parameter required to be an valid url
but the localhost url isn't valid

What should i do to run this part on my localhost ?

```php
Client::logo()->post([
    'id' => 123,
    'image' => "{File_Uploaded_Url}",
    'default' => 1
]);
```

Thanks.

**Comment by coffeetalkh** [comment]
Hi, 

@josheghani-dev we have no local image support on DynamicAd because our server can't access to your localhost address, you can google standard image sizes for this part :)

Regards,

**Comment by josheghani-dev** [comment]
Yeah i was confused 😄

Thanks,
